# CHM4390A/CHM8309A
## Lecture 2. Data analysis with Python

Part of this lecture is inspired to the "Python Scripting for Computational Molecular Science" and "Data Analysis with Python" workshop offered by the Molecular Science Software Institute (https://education.molssi.org, license: https://github.com/MolSSI-Education/python_scripting_cms/blob/gh-pages/LICENSE.md). 

### Lecture objectives
1. Learn how to work with text files
1. Learn how to use NumPy for numerical data
1. Learn how to use functions in Python
2. Learn how to use Pandas with tabular data
3. Learn how to plot data

### Required libraries
- NumPy
- Pandas
- Matplotlib

### Working with files
The MMGBSA_data.txt file in the data2 folder contains various results from the application of the Molecular Mechanics Generalized Born/Surface Area (MMGBSA) model to a ligand-receptor molecular dynamics simulation. We want to extract meaningful information from this file, without going through it manually.

In [1]:
# The following two commands can be used to list the content of the current directory and see the path of it, respectively

In [2]:
ls data2

MMGBSA_data.txt       periodic_table.csv
distances_aa.csv      periodic_table_2.csv


In [3]:
pwd

'/Users/Checco/Desktop'

In [4]:
# To import libraries or modules in python, use import followed by the name of the library
# Here we want to import the operating system (os) library that will allow us to access files

import os

file = os.path.join('data2', 'MMGBSA_data.txt')     # This ensures that will work both on Windows and Unix systems
                                                    # library.module.function structure; remember to specify the full
                                                    # path if you want to access a folder outside the current directory
print(file)


data2/MMGBSA_data.txt


In [5]:
gb_file = open(file, 'r')                 
gb_data = gb_file.readlines()            # Save the rows of the file as elements of a list
gb_file.close()

In [6]:
# Let's print the line that contains the dG, which starts with 'dG Average', i.e. the average free energy of binding over the simulation
for line in gb_data:
    if 'dG Average' in line:
        print(line)

dG Average: -91.4524



In [7]:
# Enumerate to assign the index number of the list to each line
for index,line in enumerate(gb_data):
    if 'dG Average' in line:
        print(index, line)

205 dG Average: -91.4524



In [8]:
# Split lines

for line in gb_data:
    if 'dG Average' in line:
        line_avg = line

splitted_line_energy = line_avg.split()     # Split create a list, based on the separator listed between brackets (space if not defined)
print(splitted_line_energy)

energy = splitted_line_energy[2]
print(energy)

type(energy)
energy = float(energy)                      # Cast to float value from string

['dG', 'Average:', '-91.4524']
-91.4524


In [9]:
# Write data from a list into a file; here, let's use r_l
out_f = open('r_l_out.txt', 'w')                # 'w' write, 'r' read, 'a' append, 'x' create
r_l = [0.145, 0.146, 0.147, 0.148, 0.149, 0.150, 0.151, 0.152, 0.153,
     0.154, 0.155, 0.156, 0.157, 0.158, 0.159, 0.160, 0.161]

for r in r_l:
    out_f.write(F"distance is {r}\n")          # \n is the newline character
    
out_f.close()                                  # Close the file after finishing writing

out_f_r = open('r_l_out.txt', 'r')
for r_lines in out_f_r:
    print(r_lines)

distance is 0.145

distance is 0.146

distance is 0.147

distance is 0.148

distance is 0.149

distance is 0.15

distance is 0.151

distance is 0.152

distance is 0.153

distance is 0.154

distance is 0.155

distance is 0.156

distance is 0.157

distance is 0.158

distance is 0.159

distance is 0.16

distance is 0.161



### Exercise 1 (15 minutes)
1. The 'dg Average' value is calculated as an average over all the molecular dynamics snapshots processed with the Molecular Mechanics/Generalized Born Surface Area (MMGBSA) method. Everytime a new snapshot is read by the MMGBSA program, a new line starting with 'Reading' is written to the txt file. Print out how many snapshots have been processed.
2. Two dg Average values are calculated and reported in the file (depending on the inclusion of a strain energy term, where NS indicates No Strain energy). The lines containing those values contain the string 'Average'. Print the two energy values and their line number.

### Solution

In [10]:
c=0                                   # Initialize counter

for idx,line in enumerate(gb_data):
    if 'Reading' in line:
        c += 1                        # Increase counter by 1 at each iteration
    elif 'Average' in line:
        print(idx, line.split()[2])
        
print(c)  

205 -91.4524
209 -110.2463
201


### Working with numerical data: NumPy

In [11]:
# Simple operations with numpy arrays
import numpy as np              # AS defines how the library will be called through the script
a = np.array([1, 2, 10, 5])
b = np.array([4, 3, 2, 0])
sm = a + b
print(sm)

mlp = a*b
print(mlp)

[ 5  5 12  5]
[ 4  6 20  0]


In [12]:
# Sort
a_s = np.sort(a)
print(a_s)

[ 1  2  5 10]


In [13]:
# Compare with lists
a = [1, 2, 10, 5]
b = [4, 3, 2, 0]
sm = a + b
print(sm)

[1, 2, 10, 5, 4, 3, 2, 0]


In [14]:
# Some useful operations with numpy arrays
# arange
a = np.arange(-3, +3, 1)
print(a)

[-3 -2 -1  0  1  2]


In [15]:
# Reshape
a_rs = a.reshape(2, 3)
a_rs2 = a.reshape(3, 2)
print(a_rs)
print(a_rs2)

[[-3 -2 -1]
 [ 0  1  2]]
[[-3 -2]
 [-1  0]
 [ 1  2]]


In [16]:
# Flattening multidimensional arrays
a_mltd = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a_flt = a_mltd.flatten()
print(a_mltd)
print(a_flt)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [17]:
# Broadcasting for math operations on arrays of different shape
a = np.array([(1, 2, 5, 10), (5, 4, 3, 1)])
a = np.array(a)
scale = 2
scale_vect = np.array([2, 2, 2, 2])

In [18]:
print(a, a.shape)                      # The shape command gives a the size fo each dimension, starting from the first
print(scale_vect, scale_vect.shape)

[[ 1  2  5 10]
 [ 5  4  3  1]] (2, 4)
[2 2 2 2] (4,)


In [19]:
a_s = a*scale                   # Broadcasting: "stretching" the smaller vector over all elements of the array
print(a_s)

[[ 2  4 10 20]
 [10  8  6  2]]


###### Rules for broadcasting
NumPy compares the shapes of the two arrays element-wise. It starts with the trailing (i.e. rightmost) dimensions and works its way left. Two dimensions are compatible if they are equal or one of them is 1. For broadcasting 1-d arrays, the number of elements in the 1-d array must match the number of columns in the multi-dimensional arrays. More details: https://numpy.org/doc/stable/user/basics.broadcasting.html

In [20]:
a = np.array([[1, 2, 5, 10], [5, 4, 3, 1], [1, 0, 10, 20]])
scale_vect = np.array([1, 10, 5, 3])

print(scale_vect)
print(a*scale_vect)
print(scale_vect.shape)

[ 1 10  5  3]
[[ 1 20 25 30]
 [ 5 40 15  3]
 [ 1  0 50 60]]
(4,)


In [21]:
# Matrix multiplication
a = np.array([[1, 2], [5, 4]])
b = np.array([[1, 3], [3, 4]])
mlt = a*b                       # This returns element-wise multiplication
print(a*b)

a_b_mtx = np.matmul(a, b)       # Matrix multiplication
print(np.matmul(a, b))

[[ 1  6]
 [15 16]]
[[ 7 11]
 [17 31]]


In [22]:
# Logical operations
a = np.array([1, 2, 10, 5])
a_m = a[a > 2]

print(a_m)
print(a > 2)

[10  5]
[False False  True  True]


In [23]:
# Axes 
a = np.array([[1, 2, 10, 5], [3, 4, 5, 2]])
np.mean(a, axis=0)     # axis = 0 mean by row, axis =1 mean by column

array([2. , 3. , 7.5, 3.5])

### Functions in Python

In [24]:
# Functions are useful when we want to reutilize the operation often in our code (by defining once in the script or in a module and importing it)
import numpy as np

def mult(a, b):
    """Perform multiplication."""        # Help/documentation
    m = a*b
    return m

print(mult(1, 2))
print(mult(np.array([1,2]), np.array([2,4])))

help(mult)

2
[2 8]
Help on function mult in module __main__:

mult(a, b)
    Perform multiplication.



### Pandas

In [25]:
import os
import pandas as pd

In [26]:
# Create an empty dataframe and add columns from lists or arrays
df_test = pd.DataFrame()

c1 = [str(i) for i in list(range(5))]
c2 = np.array([1,2,4,10,8])
df_test['column1'] = c1
df_test['column2'] = c2
df_test.head()

column1  column2
0       0        1
1       1        2
2       2        4
3       3       10
4       4        8

In [27]:
# Inspecting the data
df_test.info()        # Note that column 1 is an object (string) as we defined it like so

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   column1  5 non-null      object
 1   column2  5 non-null      int64 
dtypes: int64(1), object(1)
memory usage: 208.0+ bytes


In [28]:
# Read CSV files as dataframes with pandas
file = os.path.join('data2', 'periodic_table.csv')    # Use sep=';' if necessary, ie if data is separated by ;
df = pd.read_csv(file)